
---

kind: pipeline

name: deploy

workspace:

  base: /data/service

  path: /data/path

steps:

- name: hello-world

  image: docker

  settings:

    host:

      from_secret: host

    port: 22

    username:

      from_secret: ssh_name

    password:

      from_secret: ssh_passwd

    commands:
      
      - echo "hello world"

    
